name: LightWeightBackupWorldPlugin
version: '${version}'
main: com.gazim.minecraft_plugin.lightweightbackupworldplugin.LightWeightBackupWorldPlugin
api-version: 1.19
commands:
  backup: {}
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.11.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.11.0
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.0-RC
  - org.eclipse.jgit:org.eclipse.jgit:3.5.0.201409260305-r
